name: iOS Build
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Theos
        run: |
          sudo xcode-select -s /Applications/Xcode_13.4.1.app
          export THEOS=~/theos
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          curl -ksL https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz | tar -xf - -C $THEOS/sdks

      - name: Build
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ModMenu_IPA_DEB
          path: |
            packages/*.deb
            *.dylib